FRONTENDBOOTCAMP-13th/JS-09-Promise9

test-bsb.js

🧪test: Add test-bsb.js

---

src/pages/main.html
src/style.css
vite.config.js

💄style: Update base UI styles

---

prettier.config.cjs

🐋chore : Edit prettier.config.cjs

---

src/js/EmotionScore.ts

✨feat: Add emotion data saver feature

---

src/js/branch-structure.ts
src/pages/test.html

✨feat: Modify dialogue to objects

---

src/css/components.css
src/pages/main.html
src/pages/result.html
src/pages/test.html

🐛bug: Resolve font loading error

---

src/js/branch-structure.ts
src/pages/test.html

✨feat: Add dialogue to objects and add lines 

---

src/js/branch-structure.ts

✨feat: Add emotion branch

---

src/js/EmotionScore.ts
src/js/branch-structure.ts

✨feat: Add easterEgg feature

---

src/js/KakaoApi.ts

💬comment: Update KakaoApi.ts comments in conditional logic

---

src/js/bgm.ts
src/pages/test.html
src/style.css

✨feat: Add bgm feature

---

src/js/result-playmusic.ts
src/pages/main.html
src/pages/result.html
src/pages/test.html
src/style.css

♻️refactor: Adjust play-game

---

src/js/branch-structure.ts

✨feat: Store high emotion value in localStorage

---

src/js/main.ts
src/style.css

🐛bug: Edit location link

---

src/js/PlayLists.ts

✨feat: Modify emotion score check

---

src/css/components.css
src/css/result.css
src/js/branch-structure.ts
src/pages/result.html
src/pages/test.html
src/style.css

💄style: Modify easter-egg character name

---

src/js/branch-structure.ts

♻️refactor: Modify image path

---

src/js/main.ts

✨ feat: Add localStorage clear function for highScore data

---

src/js/bgm.ts
src/pages/test.html

♻️refactor: Improve bgm conditional structure

---

README.md

📝docs: Update README with project info

---

src/js/branch-structure.ts
src/pages/test.html

✨feat: Remove name tag in narration scene

---

README.md
src/css/main.css
src/js/branch-structure.ts
src/js/main.ts
src/pages/main.html
src/pages/test.html

📝docs: Update README

---

src/js/branch-structure.ts
src/js/emotion-score.ts

✨feat: Modify emotion score feature

---

src/js/branch-structure.ts
src/js/emotion-score.ts
src/js/main.ts

Feature/modify continue game/ijh

---

src/js/branch-structure.ts

✨feat: Remove nowScene in localstorage

---

index.html
src/css/index.css
src/js/index.ts
src/swiper.d.ts
src/vite-env.d.ts

✨feat: Add swiper function

---

src/css/components.css
src/css/main.css
src/js/main.ts
src/pages/main.html

♻️refactor: Improve conditional logic in main.ts and main.html

---

index.html
src/js/branch-structure.ts
src/js/kakao-api.ts
src/pages/result.html

✨feat: Add index.html OG(Open Graph)tag

---

src/js/bgm.ts
src/js/result-playmusic.ts

♻️ refactor: Refactor result-playmusic alert code

---

src/css/index.css
src/js/index.ts

💄style: Update media quiery style

---

src/css/result.css
src/js/bgm.ts
src/js/branch-structure.ts
src/js/kakao-api.ts
src/js/result-playmusic.ts
src/pages/result.html

🐛bug: Fix kakao share

---

src/style.css

🐛bug: Fix lines hide

---

src/style.css

🐛bug: Fix image size

---

src/style.css

🚀deploy: deploy

---

index.html
src/css/index.css
src/css/main.css
src/pages/dokidoki-main.html
src/pages/dokidoki-play.html
src/pages/dokidoki-result.html
src/style.css

🖥️ a11y: Update meta-tag

---

README.md

📝docs: Update READEME

---

src/css/index.css
src/js/main.ts

✏️typo: Fix comment typo

---

src/css/main.css
src/js/branch-structure.ts

🐛bug: Add forced reflow using offsetHeight after hiding prevBtn

---

src/js/bgm.ts
src/js/branch-structure.ts
src/js/result-playmusic.ts
src/pages/dokidoki-play.html

🐛bug: Fix music autoplay

---

src/js/branch-structure.ts

🐛bug: Remove touch event
